### ISSUE TITLE
No README.md

### ISSUE THREAD

**Issue by huynd2001** [minhducsun2002/osu-irc-forward#1]
How am I supposed to know what this repo does?

**Comment by minhducsun2002** [comment]
Because it is not even meant to be a proper software project.

Besides, I didn't mean for anyone else to run this code. Sure I will answer questions if possible, but should someone decide to fiddle with this, they're on their own (the code is simple as hell one might just write their own copy). I don't think the quality of something scrapped up in 3 hours would be anything to rely on either.
